apiVersion: v1
kind: Secret
metadata:
  name: neo4j-auth
  labels:
    app: neo4j
type: Opaque
stringData:
  # This corresponds to NEO4J_AUTH=neo4j/bernmobil123
  NEO4J_AUTH: "neo4j/bernmobil123"
  # This corresponds to NEO4J_server_cluster_network_shared__secret
  NEO4J_server_cluster_network_shared__secret: "BernmobilClusterGeheimnis123!"
