neo4j:
  name: "neo4j-cluster"
  # 5 Enterprise (must accept license)
  edition: "enterprise"
  acceptLicenseAgreement: "yes"

  password: "bernmobil123"
core:
  standalone: false
  numberOfServers: 3

readReplica:
  numberOfServers: 1
  # We will manage scaling via a custom HPA

volumes:
  data:
    mode: dynamic
    dynamic:
      storageClassName: "standard"
      requests:
        storage: 2Gi
  
config:
  # Additional configurations from docker-compose.yaml
  server.config.strict_validation.enabled: "false"



jvm:
  heapSize: "512m"
  pagecacheSize: "512m"
