neo4j:
  name: "neo4j-cluster"
  # 5 Enterprise (must accept license)
  edition: "enterprise"
  acceptLicenseAgreement: "yes"

  password:
    secretReference:
      name: neo4j-auth
      key: NEO4J_AUTH

core:
  standalone: false
  numberOfServers: 3

readReplica:
  numberOfServers: 1
  # We will manage scaling via a custom HPA

volumes:
  data:
    mode: dynamic
    # Default is 10Gi, we can keep it default for now
  
config:
  # Additional configurations from docker-compose.yaml
  server.config.strict_validation.enabled: "false"
  server.cluster.network.shared_secret: "${NEO4J_server_cluster_network_shared__secret}"

env:
  # We pass the shared secret dynamically via environment variable to the config
  - name: NEO4J_server_cluster_network_shared__secret
    valueFrom:
      secretKeyRef:
        name: neo4j-auth
        key: NEO4J_server_cluster_network_shared__secret

jvm:
  heapSize: "512m"
  pagecacheSize: "512m"
